### ISSUE TITLE
注册页面美化

### ISSUE THREAD

**Issue by mahone3297** [mahone3297/exchange#1]
/register/
/register/confirmed

**Comment by shenopkss** [comment]
commit c449380e7048f3836f46ff651ad44e516834c5bd

**Comment by mahone3297** [comment]
1. <link href="http://v3.bootcss.com/examples/signin/signin.css" rel="stylesheet">
不用外部链接，文件下载到本地

2. app/Resources/FOSUserBundle/views/layout.html.twig
最上面，style标签下，代码有问题，请fix
